chore(dev-deps): ⬆️ update devdependencies (non-major) (patch) (#62)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@ianvs/prettier-plugin-sort-imports](https://togithub.com/ianvs/prettier-plugin-sort-imports) | [`3.7.1` -> `3.7.2`](https://renovatebot.com/diffs/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.1/3.7.2) | [![age](https://badges.renovateapi.com/packages/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.2/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.2/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.2/compatibility-slim/3.7.1)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.2/confidence-slim/3.7.1)](https://docs.renovatebot.com/merge-confidence/) |
| [@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | [`18.15.3` -> `18.15.7`](https://renovatebot.com/diffs/npm/@types%2fnode/18.15.3/18.15.7) | [![age](https://badges.renovateapi.com/packages/npm/@types%2fnode/18.15.7/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/@types%2fnode/18.15.7/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/@types%2fnode/18.15.7/compatibility-slim/18.15.3)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/@types%2fnode/18.15.7/confidence-slim/18.15.3)](https://docs.renovatebot.com/merge-confidence/) |
| [nodemon](https://nodemon.io) ([source](https://togithub.com/remy/nodemon)) | [`2.0.21` -> `2.0.22`](https://renovatebot.com/diffs/npm/nodemon/2.0.21/2.0.22) | [![age](https://badges.renovateapi.com/packages/npm/nodemon/2.0.22/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/nodemon/2.0.22/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/nodemon/2.0.22/compatibility-slim/2.0.21)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/nodemon/2.0.22/confidence-slim/2.0.21)](https://docs.renovatebot.com/merge-confidence/) |
| [prettier](https://prettier.io) ([source](https://togithub.com/prettier/prettier)) | [`2.8.4` -> `2.8.7`](https://renovatebot.com/diffs/npm/prettier/2.8.4/2.8.7) | [![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/compatibility-slim/2.8.4)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/confidence-slim/2.8.4)](https://docs.renovatebot.com/merge-confidence/) |
| [release-it](https://togithub.com/release-it/release-it) | [`15.9.0` -> `15.9.3`](https://renovatebot.com/diffs/npm/release-it/15.9.0/15.9.3) | [![age](https://badges.renovateapi.com/packages/npm/release-it/15.9.3/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/release-it/15.9.3/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/release-it/15.9.3/compatibility-slim/15.9.0)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/release-it/15.9.3/confidence-slim/15.9.0)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>ianvs/prettier-plugin-sort-imports</summary>

### [`v3.7.2`](https://togithub.com/IanVS/prettier-plugin-sort-imports/releases/tag/v3.7.2)

[Compare Source](https://togithub.com/ianvs/prettier-plugin-sort-imports/compare/v3.7.1...v3.7.2)

#### What's Changed

-   Fix importOrderCombineTypeAndValueImports for Flow by [@&#8203;IanVS](https://togithub.com/IanVS) in [https://github.com/IanVS/prettier-plugin-sort-imports/pull/57](https://togithub.com/IanVS/prettier-plugin-sort-imports/pull/57)

**Full Changelog**: https://github.com/IanVS/prettier-plugin-sort-imports/compare/v3.7.1...v3.7.2

</details>

<details>
<summary>remy/nodemon</summary>

### [`v2.0.22`](https://togithub.com/remy/nodemon/releases/tag/v2.0.22)

[Compare Source](https://togithub.com/remy/nodemon/compare/v2.0.21...v2.0.22)

##### Bug Fixes

-   remove ts mapping if loader present ([f7816e4](https://togithub.com/remy/nodemon/commit/f7816e445b61e77dd57d5c9ccf5fa0be4f9b18a7)), closes [#&#8203;2083](https://togithub.com/remy/nodemon/issues/2083)

</details>

<details>
<summary>prettier/prettier</summary>

### [`v2.8.7`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;287)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.6...2.8.7)

[diff](https://togithub.com/prettier/prettier/compare/2.8.6...2.8.7)

##### Allow multiple decorators on same getter/setter ([#&#8203;14584](https://togithub.com/prettier/prettier/pull/14584) by [@&#8203;fisker](https://togithub.com/fisker))



```ts
// Input
class A {
  @&#8203;decorator()
  get foo () {}
  
  @&#8203;decorator()
  set foo (value) {}
}

// Prettier 2.8.6
SyntaxError: Decorators cannot be applied to multiple get/set accessors of the same name. (5:3)
  3 |   get foo () {}
  4 |   
> 5 |   @&#8203;decorator()
    |   ^^^^^^^^^^^^
  6 |   set foo (value) {}
  7 | }

// Prettier 2.8.7
class A {
  @&#8203;decorator()
  get foo() {}

  @&#8203;decorator()
  set foo(value) {}
}
```

### [`v2.8.6`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;286)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.5...2.8.6)

[diff](https://togithub.com/prettier/prettier/compare/2.8.5...2.8.6)

##### Allow decorators on private members and class expressions ([#&#8203;14548](https://togithub.com/prettier/prettier/pull/14548) by [@&#8203;fisker](https://togithub.com/fisker))



```ts
// Input
class A {
  @&#8203;decorator()
  #privateMethod () {}
}

// Prettier 2.8.5
SyntaxError: Decorators are not valid here. (2:3)
  1 | class A {
> 2 |   @&#8203;decorator()
    |   ^^^^^^^^^^^^
  3 |   #privateMethod () {}
  4 | }

// Prettier 2.8.6
class A {
  @&#8203;decorator()
  #privateMethod() {}
}
```

### [`v2.8.5`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;285)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.4...2.8.5)

[diff](https://togithub.com/prettier/prettier/compare/2.8.4...2.8.5)

##### Support TypeScript 5.0 ([#&#8203;14391](https://togithub.com/prettier/prettier/pull/14391) by [@&#8203;fisker](https://togithub.com/fisker), [#&#8203;13819](https://togithub.com/prettier/prettier/pull/13819) by [@&#8203;fisker](https://togithub.com/fisker), [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

TypeScript 5.0 introduces two new syntactic features:

-   `const` modifiers for type parameters
-   `export type *` declarations

##### Add missing parentheses for decorator ([#&#8203;14393](https://togithub.com/prettier/prettier/pull/14393) by [@&#8203;fisker](https://togithub.com/fisker))



```jsx
// Input
class Person {
  @&#8203;(myDecoratorArray[0])
  greet() {}
}

// Prettier 2.8.4
class Person {
  @&#8203;myDecoratorArray[0]
  greet() {}
}

// Prettier 2.8.5
class Person {
  @&#8203;(myDecoratorArray[0])
  greet() {}
}
```

##### Add parentheses for `TypeofTypeAnnotation` to improve readability ([#&#8203;14458](https://togithub.com/prettier/prettier/pull/14458) by [@&#8203;fisker](https://togithub.com/fisker))



```tsx
// Input
type A = (typeof node.children)[];

// Prettier 2.8.4
type A = typeof node.children[];

// Prettier 2.8.5
type A = (typeof node.children)[];
```

##### Support `max_line_length=off` when parsing `.editorconfig` ([#&#8203;14516](https://togithub.com/prettier/prettier/pull/14516) by [@&#8203;josephfrazier](https://togithub.com/josephfrazier))

If an .editorconfig file is in your project and it sets `max_line_length=off` for the file you're formatting,
it will be interpreted as a `printWidth` of `Infinity` rather than being ignored
(which previously resulted in the default `printWidth` of 80 being applied, if not overridden by Prettier-specific configuration).



```html
<!-- Input -->
<div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}/>

<!-- Prettier 2.8.4 -->
<div
  className="HelloWorld"
  title={`You are visitor number ${num}`}
  onMouseOver={onMouseOver}
/>;

<!-- Prettier 2.8.5 -->
<div className="HelloWorld" title={`You are visitor number ${num}`} onMouseOver={onMouseOver} />;
```

</details>

<details>
<summary>release-it/release-it</summary>

### [`v15.9.3`](https://togithub.com/release-it/release-it/releases/tag/15.9.3)

[Compare Source](https://togithub.com/release-it/release-it/compare/15.9.2...15.9.3)

-   Remove knip from devDependencies as it requires Node.js v16 ([`31e4f4d`](https://togithub.com/release-it/release-it/commit/31e4f4d))

### [`v15.9.2`](https://togithub.com/release-it/release-it/releases/tag/15.9.2)

[Compare Source](https://togithub.com/release-it/release-it/compare/15.9.1...15.9.2)

-   Add knip analysis to release hooks ([`88a06ea`](https://togithub.com/release-it/release-it/commit/88a06ea))
-   Fix up config for Knip v2 ([`b96d1bf`](https://togithub.com/release-it/release-it/commit/b96d1bf))
-   Add --registry argument to `npm publish` if set in `publishConfig.registry` ([`c59d55e`](https://togithub.com/release-it/release-it/commit/c59d55e))
-   Update dependencies ([`7c86856`](https://togithub.com/release-it/release-it/commit/7c86856))

### [`v15.9.1`](https://togithub.com/release-it/release-it/releases/tag/15.9.1)

[Compare Source](https://togithub.com/release-it/release-it/compare/15.9.0...15.9.1)

-   Update dependencies ([`3673754`](https://togithub.com/release-it/release-it/commit/3673754))
-   Update projects using release-it ([`c2cfc51`](https://togithub.com/release-it/release-it/commit/c2cfc51))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 12am and before 5am on saturday" in timezone Asia/Kolkata, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://app.renovatebot.com/dashboard#github/timelessco/node-ts-library-template).